### ISSUE TITLE
Daily links list is hard to read

### ISSUE THREAD

**Issue by WnndGws** [ammgws/hangouts_linkgrabber#1]
Its just a wall of text. Maybe add a new line after each link?

**Comment by ammgws** [comment]
Maybe we could pull the title text for each url as well? It would make the message twice as long though so can make it an option only thing.

**Comment by ammgws** [comment]
BTW if we proceed with the "blank line between each link" idea then it should just be a simple update of line 172.

#10m

**Comment by WnndGws** [comment]
I will find $10m to complete the job

**Comment by ammgws** [comment]
Merged #2
